"""In Task Model: Set Foreign Key stage_id to CASCADE onDelete

Revision ID: 43ec42da97ee
Revises: a412cd0aa007
Create Date: 2023-11-25 18:14:58.296017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ec42da97ee'
down_revision: Union[str, None] = 'a412cd0aa007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_stage_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'stages', ['stage_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_stage_id_fkey', 'tasks', 'stages', ['stage_id'], ['id'])
    # ### end Alembic commands ###
