"""empty message

Revision ID: fd957f8605cf
Revises: 43ec42da97ee
Create Date: 2023-12-28 14:31:13.618057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd957f8605cf'
down_revision: Union[str, None] = '43ec42da97ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('assigned_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_user_id')
    # ### end Alembic commands ###
